"""Writes docs/framework-mapping.md from src/changeproof/frameworks.py (ROADMAP Week 5).

    uv run python scripts/framework_mapping.py

The document is generated so the mapping, its sources and its proofs cannot drift apart;
tests/test_frameworks.py fails if the file differs from what this script writes.
"""

from pathlib import Path

from changeproof.frameworks import NOT_MAPPED, PLANNED, REFERENCES, Source, controls_for
from changeproof.markets import MARKETS

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "framework-mapping.md"
MARKET_ORDER = ("general", "eu-dora", "us-defense")  # RENAME: SECTION ORDER: MAIN PATH, STRONG SECOND, THEN THE REST
FRAMEWORK_NAMES = {  # RENAME: FRAMEWORK KEY TO HEADING
    "soc2": "SOC 2", "iso-27001": "ISO/IEC 27001:2022", "dora": "DORA, Regulation (EU) 2022/2554",
    "dora-rts-ict-risk": "DORA RTS on ICT risk management, Delegated Regulation (EU) 2024/1774",
    "ecb-itrq": "ECB IT Risk Questionnaire: causes of changes that caused issues",
    "eu-pqc-roadmap": "EU post-quantum cryptography roadmap", "gdpr": "GDPR",
    "nist-ssdf": "NIST SSDF", "nist-800-53-cm": "NIST SP 800-53 configuration management",
    "nist-800-53-sc": "NIST SP 800-53 system and communications protection", "swft": "SWFT", "cnsa2": "CNSA 2.0",
}
INTRO = """# Framework mapping

Generated by `scripts/framework_mapping.py` from `src/changeproof/frameworks.py`. Do not edit by hand.

Each control lists the engine output that answers it and the test or exit check that proves the
engine produces that output. Outputs marked **planned** are not built yet.

**Status** is about the control itself. "checked" with a date means its ID and topic were read in
the linked source text on that date. **unverified** means they were not: they come from the
project's own knowledge and must be checked against the source before anyone relies on them
(project rule 6). The topic column is our own short label, not the control's wording.

As of this version only the ECB IT Risk Questionnaire rows are checked (fact-check of 2026-09-27).
The EUR-Lex, AICPA and NIST pages need the owner's approval to open from the build environment.
ISO/IEC 27001 is sold by ISO, so its Annex A rows stay unverified until someone with a copy of the
standard confirms the four control numbers and titles.
"""


# PURPOSE: A MARKDOWN LINK TO A SOURCE AND ITS CHECK STATUS, AS TWO TABLE CELLS
def source_cells(source: Source) -> str:
    status = f"checked {source.checked}" if source.checked else "unverified"
    return f"[{source.title}]({source.url}) | {status}"


# PURPOSE: THE WHOLE MAPPING DOCUMENT AS MARKDOWN
def render() -> str:
    parts = [INTRO]
    for market in MARKET_ORDER:
        parts.append(f"## `{market}`\n")
        for framework in MARKETS[market].frameworks:
            parts.append(f"### {FRAMEWORK_NAMES[framework]} (`{framework}`)\n")
            controls = controls_for(framework)
            if not controls:
                parts.append(f"No controls mapped: {NOT_MAPPED[framework]}.\n")
                continue
            rows = ["| Control | Topic | Source | Status | Engine evidence | Proof |", "|---|---|---|---|---|---|"]
            for c in controls:
                outputs = "<br>".join(e.output for e in c.evidence)
                proofs = "<br>".join("**planned**" if e.proof == PLANNED else f"`{e.proof}`" for e in c.evidence)
                rows.append(f"| {c.id} | {c.topic} | {source_cells(c.source)} | {outputs} | {proofs} |")
            parts.append("\n".join(rows) + "\n")
    rows = ["| Where | Reference | Source | Status |", "|---|---|---|---|"]
    rows += [f"| {where} | {reference} | {source_cells(source)} |" for where, reference, source in REFERENCES]
    parts.append("## Other outside references in the repo\n\n" + "\n".join(rows) + "\n")
    return "\n".join(parts)


if __name__ == "__main__":
    DOC.write_text(render())
    print(f"wrote {DOC}")
